### ISSUE TITLE
Enum with associated values

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/slicec#30]
This is a proposal to add associated values to Slice enum, similar to Swift and Rust.
See:
https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html
https://doc.rust-lang.org/rust-by-example/custom_types/enum.html

The syntax of Slice enums with associated values is similar to Rust/Swift:
```
enum WebEvent
{
    PageLoad,
    PageUnload,
    KeyPress(byte key),
    Paste(string str),
    Click(long x, long y)
}
```
Syntactically, it's similar to an operation with parameters and no return value.

A Slice enum where any enumerator has one or more associated values:
 - cannot be unchecked
 - cannot have an explicit value for any of its enumerators (like = 5)
 - cannot have an underlying integer type (like `enum WebEvent : byte`)

In C#, WebEvent and its enumerators would map to a small generated record hierarchy:
```
public record WebEvent
{
    public sealed record PageLoad() : WebEvent;
    public sealed record PageUnload() : WebEvent;
    public sealed record KeyPress(byte Key) : WebEvent;
    public sealed record Paste(string Str) : WebEvent;
    public sealed record Click(long X, long Y) : WebEvent;
}
```

Usage: https://dotnetfiddle.net/LH5C6q

This also works well with switch case and switch expression, since we can match on the type (like WebEvent.KeyPress).

**Comment by InsertCreativityHere** [comment]
In languages like C# that don't have native support for these,
enums will have 2 very-different mappings (let's run with C#):
- 'normal' enums get mapped to `enum`
- 'assocated value' enums get mapped to nested `record classes`

This proposal says the deciding factor will be "is there an underlying type?"
- `yes` -> it's a normal enum
- `no` -> it's an assocated value enum

This produces a bad mapping for the most common kind of enum:
those with neither associated values nor underlying types.
```
enum MyEnum {
    Foo,
    Bar,
}
```
These are the cleanest looking enums, and the one that users will initially reach for.

But will get treated as enums with associated values, and mapped 'poorly' in many languages:
A C# developed will find a bunch of empty `record class`es nested together, instead of an `enum`.
A C++ developer will find a `variant` of `monostate`s, instead of an `enum class`.
etc.
All of these will surprising to users, and harder to use.

**In my opinion, this decision (which mapping to use) should be based on `are there associated values`, and _not_ `is there an underlying value`. Using this criterion results in more natural mappings more often.**

I think it's worth stating that _most_ languages do not support associated values. C# doesn't, Kotlin doesn't, Typescript doesn't, Python doesn't, Go doesn't even have enums, let alone with associated values.
Of course we can find ways to _emulate_ associated values, but having that be the 'default' mapping is suboptimal.

Ensuring that these languages have natural, expected mappings out-of-the-box is more important than optimizing the syntax of enums for the 2 languages (Rust and Swift) that can properly use this new feature.

---

P.S. I just _feel_ like normal enums should be the default in my gut.

**Comment by InsertCreativityHere** [comment]
A concern I anticipate is: "future extensibility".
Making 'normal' enums the default means that adding an associated value is a breaking change.
```
// For example, going from `A` to `B` would be a breaking change.
enum A { Foo, Bar }
enum B { Foo, Bar(b: bool) }
```

You are correct, but "future extensibility" is unsolvable here. With the current proposal, this is already a breaking change:
```
enum A { Foo, Bar }
enum B { Foo, Bar = 5 }
```

----

No matter which choice we make, we will be loosing one form of extensibility.
Either the ability to add associated values, or the ability to add 'raw values'.

**Comment by bernardnormier** [comment]
>  With the current proposal, this is already a breaking change:

That's not correct. The current proposal doesn't allow you to assign a value to  an enumerator when the enumeration has no underlying type.

**Comment by InsertCreativityHere** [comment]
Parser support for enums with associated values was added in #664.
